# Generated by Django 4.0.4 on 2022-05-16 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Spending',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=100)),
                ('amount', models.IntegerField()),
                ('spent_at', models.DateTimeField()),
                ('currency', models.CharField(max_length=10)),
            ],
        ),
    ]
